### PR TITLE
 #Commit 1 : Splash & login screen

### PR DESCRIPTION
**Pull request by GopalDan**
Hello eveyone
This is Gopal . I have made the following changes-
1 Change the layout of splash screen
2 change the layout of login screen
3 change the color of  title bar

### CODE REVIEW

**Comment by DivyaThakur24** [comment]
No files in your _drawable_ folder **Gopal**
Please **rectify** it and 
Send us your **valuable PR** again 🤞

**Comment by GopalDan** [comment]
Hey @DivyaThakur24 But I checked in android studio files are their . So now what I have to do .

**Comment by DivyaThakur24** [comment]
It's running perfectly now **Gopal**
Awesome Design 👌 👍 
Thank you for the contribution 🙂

**Comment by amy6** [comment]
Cool logo :cool: Thank you @GopalDan for your contributions! :v: Congratulations on your successful PR. :clap: 
We shall now be moving on to our next activity. We will share the details on the same in #cp_desgn_app channel.

**Pull request closed without merging**
