### PR TITLE
Implement RecyclerView with Staggered Grid Layout Manager

### PR DESCRIPTION
**Pull request by numerative**
I agree that it is a simple looking layout, but I am proud that it does get a few things right. 

Video: https://www.youtube.com/watch?v=_Bs5rg0zDrI
### Here's a rundown:
- Images have rounded corners.
- Max Height of each Card is set so as to prevent extra long images from taking up space.
- Width of the image never exceeds card width.
- Being short on time, I was only able to get images; wanted to include labels too.

### Issues:
- First set of images on Screen are not correctly `ScaleType`d. However, scrolling up and down solves it. Also, issue doesn't appear on any Emulator Devices I tested.
- Images are stored locally and not on Firebase. But, integration with code should be easy.

Video: https://www.youtube.com/watch?v=_Bs5rg0zDrI

screen

### CODE REVIEW

**Comment by DivyaThakur24** [comment]
Merge Conflicts have been **Resolved**
Thank you for the Contribution !!

**Comment by numerative** [comment]
Thank You for resolving the conflicts, @DivyaThakur24! 😃

**Comment by amy6** [comment]
Hi @numerative , your code looks great! :ok_hand: except for one thing - it's stated that we'll be using Firebase adapters for our app. So you'll need to use the same instead. Please make the changes and send us your updated PR to the `development` branch.
Thank you for contributing! :v: Let is know if you need any help.

**Comment by numerative** [comment]
I'll try it and update the code. Will surely ask for help when needed. Thanks! 🙂

**Pull request closed without merging**
