### PR TITLE
Commit #1

### PR DESCRIPTION
**Pull request by Shubham6059**
1. Added SpashScreen with given Logo and Background.
2. Added LoginScreen with a custom gradient background and with displayed GoogleSignIn option.
3. Added the Launcher_Icon for App.

login_screen
splash_screen

### CODE REVIEW

**Comment by kupuriandingu** [comment]
Love the colour scheme @Shubham6059 . Thanks a lot for your contribution 🙂

**Comment by DivyaThakur24** [comment]
Awesome Colors **Shubham** 👌 👍 
But Please do sync your forked repo with ours!
There are some merge conflicts!
Thank you for your contribution 🙂

**Comment by Shubham6059** [comment]
Merged the conflicts @DivyaThakur24 @kupuriandingu. Please have a look if this works.

**Comment by amy6** [comment]
@Shubham6059 great design! :clap: :ok_hand: Thank you for contributing!
However, there still exist a few issues because of the merge conflicts. Please check again. Currently closing this PR as we will be moving on to the next activity.

Feel free to reach out to us on #cp_design_app in case of any queries.

**Pull request closed without merging**
