### PR TITLE
Splash & Login Screen

### PR DESCRIPTION
**Pull request by rohitvivek**
Splash & Login Screen

### CODE REVIEW

**Comment by rohitvivek** [comment]
giphy 1

**Comment by rohitvivek** [comment]
giphy 3

**Comment by rohitvivek** [comment]
giphy 4

**Comment by rohitvivek** [comment]
giphy 5

**Comment by amy6** [comment]
Thank you @rohitvivek for your contributions! :v: Congratulations on your successful PR. :clap: 
We shall now be moving on to our next activity. We will share the details on the same in #cp_desgn_app channel.

**Pull request closed without merging**
