### PR TITLE
PR #3 RecyclerView with Firebase

### PR DESCRIPTION
**Pull request by numerative**
Finally RecyclerView works with Firebase.
untitled
There are many issues related to performance and card layout, but they something that can be ironed out with joint efforts. Important part is that the code works.

Now, I believe that this will not work right off the bat on your devices because my JSON file is not uploaded. So, I am attaching a screenshot of the present data structure.

capture

Issues:
- Glide requires its targetImageView to be of fixed dimensions, hence the grid is laid out in an equal 2 x 1 pattern.
- Only 4 images have been uploaded but sometimes 5 are displayed - the last one appears twice.

This also fixes issues introduced in activity_splashscreen with merge of #74 . ✌️ 

`Slack Id: @Michael Hathi`

### CODE REVIEW

**Comment by amy6** [comment]
Amazing job @numerative :clap: :clap: Sure, we shall sit together and review it! :v:

**Comment by amy6** [comment]
Hi @numerative we've reviewed your changes. Looks like you have used `Firestore` instead of `Firebase Realtime Database` which is the expected requirement.

**Comment by numerative** [comment]
That's true @amy6.
But that's because I found a tutorial which implemented the above for the same purpose as design villa. So, I thought this would be the right choice. 

I am sorry for this mistake, I still need to learn about firebase.

**Comment by amy6** [comment]
There's no need to be sorry @numerative :sweat_smile:
You have done a great job implementing this!! Please note that it's highly appreciated. :blush: :heart: We shall connect with you regarding the details! :v: Thank you :smile:

**Comment by numerative** [comment]
Thanks, I'll try my best to correct it.

**Comment by FLYINGKRIPTO** [comment]
thankyou for your contribution @numerative

**Pull request closed without merging**
