### PR TITLE
AnimatedSplashActivity

### PR DESCRIPTION
**Pull request by Sheetalpamecha**
Commit#1 Feature -  Add animation to the splash activity. Create mytransition.xml file. 
Commit#2 Update SDKversion to 27 from 26; No production code changed

### CODE REVIEW

**Comment by kupuriandingu** [comment]
@Sheetalpamecha your res/anim/mytransition.xml file does not contain any code.

**Comment by kupuriandingu** [comment]
Oh, i see it now. You don't commit before, thats why.

**Comment by amy6** [comment]
Thank you @Sheetalpamecha for your contributions! Good job on the splash screen! :v: There are some unresolved merge conflicts, so please take a look.

Feel free to reach out to us on #cp_design_app in case of any queries.

**Comment by amy6** [comment]
Closing the PR (please see the above comments)

**Pull request closed without merging**
