### PR TITLE
Splash & Login commit#1

### PR DESCRIPTION
**Pull request by DSdatsme**
screenshot_1523897201
screenshot_1523897165
screenshot_1523897175

***What i have added?***
Splash Screen
>Animated progress bar
>background
>tagline fade in animation

Login screen
>few textviews
>gradient animated background
>google sign in button
loggin in textview with show/hide animation for showing user login status(progress)

### CODE REVIEW

**Comment by kupuriandingu** [comment]
Looking great @DSdatsme There are is a typo on the first screen, other than that it's awesome 👌

**Comment by DSdatsme** [comment]
Yea thanks for pointing that out @kupuriandingu 
Well they are just typos so they'll be fixed whenever required 😜
And other thing I want to tell is I have used hard-coded dimensions and strings ,as I was in। a hurry to complete this,hope u consider that 😆

**Comment by kupuriandingu** [comment]
Will consider that when we choose from the PR 😝😝 Better extract them 😜

**Comment by amy6** [comment]
Amazing job with the color transitions for the login screen :ok_hand: :ok_hand: Thank you @DSdatsme for your contributions! :v: Congratulations on your successful PR. :clap: 
We shall now be moving on to our next activity. We will share the details on the same in #cp_desgn_app channel.

**Pull request closed without merging**
