### PR TITLE
Design the UI for Splash Screen and Login Screen using the constraint layout

### PR DESCRIPTION
**Pull request by modfa**
(1) Design the splash screen UI using the Constraint Layout for more responsive design.
(2) Design the login screen UI using the Constraint Layout for more responsive design.
(3) Avoided using the hard-coded values and place them into the appropriate resource files for best android practices.
(4) Also used scrollView so it can be easy to use in Landscape mode or large screen devices.

screenshot_20180417-132554
screenshot_20180417-132622

### CODE REVIEW

**Comment by DivyaThakur24** [comment]
**MODF** there are some merge conflicts in just _3 files_ of yours!
Please remove them and send us a **PR** again!
Thanks for your precious contribution 🙂

**Comment by modfa** [comment]
I tried to resolve the conflicts.
Please check now and let me know the further steps.
Thanks

**Comment by DivyaThakur24** [comment]
Awesome Work 👍  **MODF**
_Minimalistic Design_ 👌 
Thanks for correcting it !! 🙂

**Comment by amy6** [comment]
Great design for the logo @modfa ! :clap: Congratulations on your successful PR. You are one of the top contributors. Thank you for your contributions. 
We shall now be moving on to our next activity. We will share the details on the same in #cp_desgn_app channel.

**Pull request closed without merging**
