### PR TITLE
Added the firebase storage and firebase adapter for the staggered view

### PR DESCRIPTION
**Pull request by kingsammalik**
I have added the firebase storage and firebase adapter to the home fragment.
Also I changed the activity_home.xml a bit, the action bar was overlapping with the frame layout.
Add the images in the firebase storage, and add the url in the firebase database in the prescribed format.
Please do take the likes as string instead of long as prescribed in the format given by moderator.
device-2018-05-08-202513

### CODE REVIEW

**Comment by FLYINGKRIPTO** [comment]
looks awesome!! 🏆 
great Job 👏 
Thank you for your contribution 👍 🥇

**Comment by amy6** [comment]
Great job @kingsammalik . We shall review the code and get back to you :clap: 
Thank you for your contributions :heart:

**Comment by kingsammalik** [comment]
screen shot 2018-05-10 at 10 21 20 pm

**Comment by FLYINGKRIPTO** [comment]
Thankyou for contribution @kingsammalik

**Comment by FLYINGKRIPTO** [comment]
Thankyou for your contribution to Design Villa @kingsammalik

**Pull request closed without merging**
